[package]
name = "rasp"
version = "0.1.0"
authors = ["Michael Spencer <sonrisesoftware@gmail.com>"]

[dependencies]
nom = { version = "4.0.0", features = ["verbose-errors"] }
itertools = "0.7.8"
runtime-fmt = "0.3.0"
